/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.programacion.view;

/**
 *
 * @author alexr
 */
public class HanoiView extends javax.swing.JFrame {

  /**
   * Creates new form MainView
   */
  public HanoiView() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTableTorreA = new javax.swing.JTable();
        jTableTorreB = new javax.swing.JTable();
        jTableTorreC = new javax.swing.JTable();
        jLabelAB = new javax.swing.JLabel();
        jLabelAC = new javax.swing.JLabel();
        jLabelBA = new javax.swing.JLabel();
        jLabelBC = new javax.swing.JLabel();
        jLabelCA = new javax.swing.JLabel();
        jLabelCB = new javax.swing.JLabel();
        jComboBoxDiscos = new javax.swing.JComboBox<>();
        jLabelMinimoMovimientos = new javax.swing.JLabel();
        jLabelNumeroMovimientos = new javax.swing.JLabel();
        jLabelIniciar = new javax.swing.JLabel();
        jLabelResolver = new javax.swing.JLabel();
        jLabelReiniciar = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setTitle("Agregar Producto");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableTorreA.setBackground(new java.awt.Color(255, 255, 255));
        jTableTorreA.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTableTorreA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTableTorreA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Torre A"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTorreA.setAutoscrolls(false);
        jTableTorreA.setFocusable(false);
        jTableTorreA.setRowSelectionAllowed(false);
        jPanel1.add(jTableTorreA, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 143, 175, 200));
        if (jTableTorreA.getColumnModel().getColumnCount() > 0) {
            jTableTorreA.getColumnModel().getColumn(0).setResizable(false);
        }

        jTableTorreB.setBackground(new java.awt.Color(255, 255, 255));
        jTableTorreB.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTableTorreB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTableTorreB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Torre B"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTorreB.setAutoscrolls(false);
        jTableTorreB.setFocusable(false);
        jTableTorreB.setRowSelectionAllowed(false);
        jPanel1.add(jTableTorreB, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 143, 175, 200));
        if (jTableTorreB.getColumnModel().getColumnCount() > 0) {
            jTableTorreB.getColumnModel().getColumn(0).setResizable(false);
        }

        jTableTorreC.setBackground(new java.awt.Color(255, 255, 255));
        jTableTorreC.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTableTorreC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTableTorreC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Torre C"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTorreC.setAutoscrolls(false);
        jTableTorreC.setFocusable(false);
        jTableTorreC.setRowSelectionAllowed(false);
        jPanel1.add(jTableTorreC, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 143, 175, 200));
        if (jTableTorreC.getColumnModel().getColumnCount() > 0) {
            jTableTorreC.getColumnModel().getColumn(0).setResizable(false);
        }

        jLabelAB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/letra-b.png"))); // NOI18N
        jLabelAB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelAB, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 364, -1, -1));

        jLabelAC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/letra-c.png"))); // NOI18N
        jLabelAC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 364, -1, -1));

        jLabelBA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/letra-a.png"))); // NOI18N
        jLabelBA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelBA, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 364, -1, -1));

        jLabelBC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/letra-c.png"))); // NOI18N
        jLabelBC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelBC, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 364, -1, -1));

        jLabelCA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/letra-a.png"))); // NOI18N
        jLabelCA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 364, -1, -1));

        jLabelCB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/letra-b.png"))); // NOI18N
        jLabelCB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 364, -1, -1));

        jComboBoxDiscos.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxDiscos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jComboBoxDiscos.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxDiscos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "4", "5", "6", "7", "8", "9", "10" }));
        jPanel1.add(jComboBoxDiscos, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 445, 225, 30));

        jLabelMinimoMovimientos.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.foreground"));
        jLabelMinimoMovimientos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelMinimoMovimientos.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMinimoMovimientos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMinimoMovimientos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabelMinimoMovimientos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelMinimoMovimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 490, 225, 30));

        jLabelNumeroMovimientos.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.foreground"));
        jLabelNumeroMovimientos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelNumeroMovimientos.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNumeroMovimientos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNumeroMovimientos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabelNumeroMovimientos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelNumeroMovimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 545, 225, 30));

        jLabelIniciar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelIniciar.setForeground(new java.awt.Color(0, 0, 0));
        jLabelIniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 610, 160, 45));

        jLabelResolver.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelResolver.setForeground(new java.awt.Color(0, 0, 0));
        jLabelResolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelResolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 610, 160, 45));

        jLabelReiniciar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelReiniciar.setForeground(new java.awt.Color(0, 0, 0));
        jLabelReiniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 610, 160, 45));

        jLabelBackground.setBackground(new java.awt.Color(255, 255, 255));
        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hanoi.png"))); // NOI18N
        jPanel1.add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger
        .getLogger(HanoiView.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger
        .getLogger(HanoiView.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger
        .getLogger(HanoiView.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger
        .getLogger(HanoiView.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
          new HanoiView().setVisible(true);
        }
      }
    );
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> jComboBoxDiscos;
    public javax.swing.JLabel jLabelAB;
    public javax.swing.JLabel jLabelAC;
    public javax.swing.JLabel jLabelBA;
    public javax.swing.JLabel jLabelBC;
    private javax.swing.JLabel jLabelBackground;
    public javax.swing.JLabel jLabelCA;
    public javax.swing.JLabel jLabelCB;
    public javax.swing.JLabel jLabelIniciar;
    public javax.swing.JLabel jLabelMinimoMovimientos;
    public javax.swing.JLabel jLabelNumeroMovimientos;
    public javax.swing.JLabel jLabelReiniciar;
    public javax.swing.JLabel jLabelResolver;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTable jTableTorreA;
    public javax.swing.JTable jTableTorreB;
    public javax.swing.JTable jTableTorreC;
    // End of variables declaration//GEN-END:variables
}
