/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.programacion.view;

/**
 *
 * @author alexr
 */
public class HanoiView extends javax.swing.JFrame {

  /**
   * Creates new form MainView
   */
  public HanoiView() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPaneA = new javax.swing.JScrollPane();
        jTableTorreA = new javax.swing.JTable();
        jScrollPaneB = new javax.swing.JScrollPane();
        jTableTorreB = new javax.swing.JTable();
        jScrollPaneC = new javax.swing.JScrollPane();
        jTableTorreC = new javax.swing.JTable();
        jLabelAB = new javax.swing.JLabel();
        jLabelAC = new javax.swing.JLabel();
        jLabelBA = new javax.swing.JLabel();
        jLabelBC = new javax.swing.JLabel();
        jLabelCA = new javax.swing.JLabel();
        jLabelCB = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxDiscos = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabelMinimoMovimientos = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelNumeroMovimientos = new javax.swing.JLabel();
        jButtonIniciar = new javax.swing.JButton();
        jButtonReiniciar = new javax.swing.JButton();
        jButtonResolver = new javax.swing.JButton();
        jLabelBackground = new javax.swing.JLabel();

        setTitle("Agregar Producto");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableTorreA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTableTorreA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Torre A"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTorreA.setAutoscrolls(false);
        jTableTorreA.setFocusable(false);
        jTableTorreA.setRowSelectionAllowed(false);
        jScrollPaneA.setViewportView(jTableTorreA);
        if (jTableTorreA.getColumnModel().getColumnCount() > 0) {
            jTableTorreA.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel1.add(jScrollPaneA, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 200, 250));

        jTableTorreB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTableTorreB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Torre B"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTorreB.setAutoscrolls(false);
        jTableTorreB.setFocusable(false);
        jTableTorreB.setRowSelectionAllowed(false);
        jScrollPaneB.setViewportView(jTableTorreB);
        if (jTableTorreB.getColumnModel().getColumnCount() > 0) {
            jTableTorreB.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel1.add(jScrollPaneB, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 200, 250));

        jTableTorreC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTableTorreC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Torre C"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTorreC.setAutoscrolls(false);
        jTableTorreC.setFocusable(false);
        jTableTorreC.setRowSelectionAllowed(false);
        jScrollPaneC.setViewportView(jTableTorreC);
        if (jTableTorreC.getColumnModel().getColumnCount() > 0) {
            jTableTorreC.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel1.add(jScrollPaneC, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 200, 250));

        jLabelAB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/letra-b.png"))); // NOI18N
        jLabelAB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelAB, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        jLabelAC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/letra-c.png"))); // NOI18N
        jLabelAC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));

        jLabelBA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/letra-a.png"))); // NOI18N
        jLabelBA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelBA, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, -1));

        jLabelBC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/letra-c.png"))); // NOI18N
        jLabelBC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelBC, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, -1));

        jLabelCA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/letra-a.png"))); // NOI18N
        jLabelCA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, -1, -1));

        jLabelCB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/letra-b.png"))); // NOI18N
        jLabelCB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabelCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Número de discos");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 420, 200, 40));

        jComboBoxDiscos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jComboBoxDiscos.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxDiscos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "4", "5", "6", "7", "8", "9", "10" }));
        jPanel1.add(jComboBoxDiscos, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 150, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Número min. mov.");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 470, 200, 40));

        jLabelMinimoMovimientos.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.foreground"));
        jLabelMinimoMovimientos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelMinimoMovimientos.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMinimoMovimientos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMinimoMovimientos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabelMinimoMovimientos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelMinimoMovimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, 150, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Número de movimientos");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 520, 200, 40));

        jLabelNumeroMovimientos.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.foreground"));
        jLabelNumeroMovimientos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelNumeroMovimientos.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNumeroMovimientos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNumeroMovimientos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabelNumeroMovimientos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelNumeroMovimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, 150, 40));

        jButtonIniciar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonIniciar.setText("Iniciar");
        jPanel1.add(jButtonIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 585, 150, 40));

        jButtonReiniciar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonReiniciar.setText("Reiniciar");
        jPanel1.add(jButtonReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 585, 150, 40));

        jButtonResolver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonResolver.setText("Resolver");
        jPanel1.add(jButtonResolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 585, 150, 40));

        jLabelBackground.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger
        .getLogger(HanoiView.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger
        .getLogger(HanoiView.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger
        .getLogger(HanoiView.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger
        .getLogger(HanoiView.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
          new HanoiView().setVisible(true);
        }
      }
    );
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonIniciar;
    public javax.swing.JButton jButtonReiniciar;
    public javax.swing.JButton jButtonResolver;
    public javax.swing.JComboBox<String> jComboBoxDiscos;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jLabelAB;
    public javax.swing.JLabel jLabelAC;
    public javax.swing.JLabel jLabelBA;
    public javax.swing.JLabel jLabelBC;
    private javax.swing.JLabel jLabelBackground;
    public javax.swing.JLabel jLabelCA;
    public javax.swing.JLabel jLabelCB;
    public javax.swing.JLabel jLabelMinimoMovimientos;
    public javax.swing.JLabel jLabelNumeroMovimientos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPaneA;
    private javax.swing.JScrollPane jScrollPaneB;
    private javax.swing.JScrollPane jScrollPaneC;
    public javax.swing.JTable jTableTorreA;
    public javax.swing.JTable jTableTorreB;
    public javax.swing.JTable jTableTorreC;
    // End of variables declaration//GEN-END:variables
}
